# Generated by Django 3.1.6 on 2021-02-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_logo', models.ImageField(upload_to='', verbose_name='Логотип в шапке сайта')),
                ('bot_logo', models.ImageField(upload_to='', verbose_name='Логотип в подвале сайта')),
            ],
            options={
                'verbose_name': 'Логотип компании',
                'verbose_name_plural': 'Логотипы компании',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='partner_logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Партнер')),
                ('partner_logos', models.ImageField(upload_to='', verbose_name='Логотипы партнеров')),
            ],
            options={
                'verbose_name': 'Логотип парнера',
                'verbose_name_plural': 'Логотипы партнеров',
                'ordering': ['-pk'],
            },
        ),
    ]
