# Generated by Django 3.1.6 on 2021-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_logo',
            name='bot_logo',
        ),
        migrations.AddField(
            model_name='company_logo',
            name='top_logo_mobile',
            field=models.ImageField(default=0, upload_to='', verbose_name='Логотип в шапке сайта (мобильный)'),
            preserve_default=False,
        ),
    ]
