# Generated by Django 3.1.6 on 2021-02-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210226_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15, verbose_name='Телефон(факс)')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Адрес, телефон и почта',
                'verbose_name_plural': 'Контактные данные компании',
                'ordering': ['pk'],
            },
        ),
    ]
