# Generated by Django 3.1.6 on 2021-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_logo',
            name='bot_logo',
            field=models.ImageField(default=0, upload_to='', verbose_name='Логотип в подвале сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='address',
            field=models.CharField(default=0, max_length=80, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
