# Generated by Django 3.1.6 on 2021-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20210226_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 150 символов включая пробелы.', max_length=150, verbose_name='Заголовок')),
                ('slogan', models.CharField(help_text='Не более 60 символов включая пробелы.', max_length=60, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
                'ordering': ['pk'],
            },
        ),
    ]
