# Generated by Django 3.1.6 on 2021-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='features',
            field=models.TextField(default=0, verbose_name='Особенности'),
            preserve_default=False,
        ),
    ]
