# Generated by Django 3.1.6 on 2021-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_title_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(max_length=180, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(help_text='Не более 200 символов включая пробелы.', max_length=200, verbose_name='Заголовок'),
        ),
    ]
