# Generated by Django 3.1.6 on 2021-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_auto_20210226_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Изображение рядом с особенностью'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='features',
            field=models.TextField(verbose_name='Особенность'),
        ),
    ]
