# Generated by Django 3.1.6 on 2021-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_age_group_category_courses_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 150 символов включая пробелы', max_length=150, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title_image', models.ImageField(upload_to='', verbose_name='Главное изображение')),
                ('image', models.ImageField(blank=True, help_text='Не обязательно для заполнения.', null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-pk'],
            },
        ),
    ]
