# Generated by Django 3.1.6 on 2021-02-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=0, help_text='Например "баннер главной страницы", "банер страницы курсов" и т.д.', max_length=50, verbose_name='Назначение баннера'),
            preserve_default=False,
        ),
    ]
