# Generated by Django 3.1.6 on 2021-02-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_title_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='name',
        ),
    ]
