# Generated by Django 3.1.6 on 2021-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_remove_title_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default=0, help_text='Слаг должен быть уникальным. ', verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
