# Generated by Django 3.1.6 on 2021-02-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(help_text='Слаг должен быть уникальным. ', unique=True, verbose_name='Слаг'),
        ),
    ]
