# Generated by Django 3.1.6 on 2021-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_auto_20210226_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='document',
            field=models.ManyToManyField(help_text='Выделите нужные документы использую клавишу "ctrl"', related_name='doc', to='learning.Documents', verbose_name='Документы'),
        ),
    ]
